const PROVINCE_MAP: Record<string, string> = {
  'buenos aires': 'B',
  'ciudad autónoma de buenos aires': 'C',
  'caba': 'C',
  'córdoba': 'X',
  'cordoba': 'X',
  'santa fe': 'S',
  'mendoza': 'M',
  'tucumán': 'T',
  'tucuman': 'T',
  'salta': 'A',
  'entre ríos': 'E',
  'entre rios': 'E',
  'misiones': 'N',
  'chaco': 'H',
  'corrientes': 'W',
  'santiago del estero': 'G',
  'san juan': 'J',
  'jujuy': 'Y',
  'río negro': 'R',
  'rio negro': 'R',
  'neuquén': 'Q',
  'neuquen': 'Q',
  'formosa': 'P',
  'chubut': 'U',
  'san luis': 'D',
  'catamarca': 'K',
  'la rioja': 'F',
  'la pampa': 'L',
  'santa cruz': 'Z',
  'tierra del fuego': 'V',
}

export const toProvinceCode = (province: string): string =>
  PROVINCE_MAP[province.toLowerCase().trim()] ?? province.slice(0, 2).toUpperCase()
